"""empty message

Revision ID: 066a8e8613c9
Revises: 0a0d276e8cf7
Create Date: 2020-06-09 15:18:22.236424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '066a8e8613c9'
down_revision = '0a0d276e8cf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
